# Utilisation de Maven pour compiler le code Java
FROM maven:3.8.4-openjdk-17 AS build
WORKDIR /app

# On copie les fichiers de configuration et le code source
COPY pom.xml .
COPY src ./src

# Compilation du projet en ignorant les tests pour aller plus vite
RUN mvn clean package -DskipTests

# Étape finale : on lance l'application
FROM openjdk:17-jdk-slim
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]